// Generated by CoffeeScript 1.4.0
(function() {

  exports.startServer = function(port, path, callback) {
    var app, express, http, routes;
    express = require('express');
    routes = require('./routes');
    path = require('path');
    http = require('http');
    app = express();
    app.configure(function() {
      app.set('views', path.join(__dirname, 'views'));
      app.set('view engine', 'jade');
      app.use(express.favicon());
      app.use(express.logger('dev'));
      app.use(express.bodyParser());
      app.use(express.methodOverride());
      app.use(express.cookieParser('your secret here'));
      app.use(express.session());
      app.use(app.router);
      return app.use(express["static"](path.join(__dirname, 'public')));
    });
    app.configure('development', function() {
      return app.use(express.errorHandler());
    });
    app.get('/', routes.list);
    return http.createServer(app).listen(port, function() {
      console.log("Express server listening on port " + port);
      return callback();
    });
  };

}).call(this);
